"use client";

import { Circle, Send, Trash2, X } from "lucide-react";
import { FormEvent, KeyboardEvent, useCallback, useEffect, useLayoutEffect, useRef, useState } from "react";
import { supabase } from "@/lib/supabase/public";
import { trackEvent } from "@/lib/analytics";

type Message = { id: string; body: string; created_at: string; sender_name: string; sender_avatar_url: string | null; can_delete: boolean };
type Page = { messages?: Message[]; has_more?: boolean; next_cursor?: string | null; can_post?: boolean; error?: string };
type BroadcastInvalidation = { payload?: { message_id?: string; operation?: string } };
const sortMessages = (rows: Message[]) => Array.from(new Map(rows.map((row) => [row.id, row])).values()).sort((left, right) => left.created_at.localeCompare(right.created_at) || left.id.localeCompare(right.id));
function initials(name: string) { return name.trim().split(/\s+/).map((part) => part.slice(0, 1)).join("").slice(0, 2).toUpperCase() || "E"; }
function safeAvatarUrl(value: string | null) { try { const url = value ? new URL(value) : null; return url?.protocol === "https:" ? url.toString() : null; } catch { return null; } }
function ChatAvatar({ name, src }: { name: string; src: string | null }) {
  const [failed, setFailed] = useState(false); const avatarUrl = failed ? null : safeAvatarUrl(src);
  return avatarUrl ? (
    // eslint-disable-next-line @next/next/no-img-element
    <img src={avatarUrl} alt={`${name}'s avatar`} onError={() => setFailed(true)} className="mt-0.5 h-8 w-8 shrink-0 rounded-xl border border-slate-200 bg-slate-50 object-cover" />
  ) : <div aria-hidden className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-xl border border-slate-200 bg-gradient-to-br from-blue-100 to-slate-100 text-xs font-bold text-blue-700">{initials(name)}</div>;
}

export default function CommunityChatPanel({ onClose }: { onClose: () => void }) {
  const [messages, setMessages] = useState<Message[]>([]), [body, setBody] = useState(""), [error, setError] = useState(""), [sending, setSending] = useState(false), [deleting, setDeleting] = useState<string | null>(null), [composing, setComposing] = useState(false), [cursor, setCursor] = useState<string | null>(null), [hasMore, setHasMore] = useState(false), [loadingOlder, setLoadingOlder] = useState(false), [unread, setUnread] = useState(0), [canPost, setCanPost] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null), prependRef = useRef<{ height: number; top: number } | null>(null);
  const refresh = useCallback(async () => { const response = await fetch("/api/community-chat/messages", { cache: "no-store" }); const page = await response.json() as Page; if (!response.ok) throw new Error(page.error ?? "Chat is unavailable."); setMessages((current) => sortMessages([...current, ...(page.messages ?? [])])); setCursor((current) => current === null ? page.next_cursor ?? null : current); setHasMore((current) => current || Boolean(page.has_more)); setCanPost(Boolean(page.can_post)); }, []);
  const nearBottom = () => { const element = scrollRef.current; return !element || element.scrollHeight - element.scrollTop - element.clientHeight < 48; };
  useLayoutEffect(() => { const pending = prependRef.current, element = scrollRef.current; if (pending && element) { element.scrollTop = pending.top + (element.scrollHeight - pending.height); prependRef.current = null; } }, [messages]);
  useEffect(() => { let active = true; trackEvent("community_chat_open", { event_category: "engagement" }); refresh().catch(() => active && setError("Chat is unavailable right now.")); const channel = supabase.channel("community-chat").on("broadcast", { event: "chat_changed" }, (event: BroadcastInvalidation) => { if (!active) return; if (event.payload?.operation === "UPDATE" && event.payload.message_id) { setMessages((current) => current.filter((message) => message.id !== event.payload?.message_id)); return; } const wasNearBottom = nearBottom(); refresh().then(() => { if (wasNearBottom) scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight }); else setUnread((current) => current + 1); }).catch(() => undefined); }).subscribe((status) => { if (status === "CHANNEL_ERROR" || status === "TIMED_OUT") setError("Live updates are temporarily unavailable."); }); return () => { active = false; supabase.removeChannel(channel); }; }, [refresh]);
  async function send(event?: FormEvent) { event?.preventDefault(); if (!canPost || !body.trim() || body.length > 500 || sending) return; setSending(true); setError(""); try { const response = await fetch("/api/community-chat/messages", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ body, clientMessageId: crypto.randomUUID() }) }); const payload = await response.json(); if (!response.ok) { setError(payload.error ?? "Unable to send message."); await refresh(); return; } setBody(""); await refresh(); trackEvent("community_chat_send", { event_category: "engagement" }); } catch { setError("Unable to send message."); } finally { setSending(false); } }
  async function remove(id: string) { if (deleting) return; setDeleting(id); setError(""); try { const response = await fetch("/api/community-chat/messages", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ id }) }); if (!response.ok) { const payload = await response.json(); setError(payload.error ?? "Unable to remove message."); await refresh(); return; } setMessages((current) => current.filter((message) => message.id !== id)); } catch { setError("Unable to remove message."); } finally { setDeleting(null); } }
  function keydown(event: KeyboardEvent<HTMLTextAreaElement>) { if (event.key === "Enter" && !event.shiftKey && !composing) { event.preventDefault(); void send(); } }
  async function loadOlder() { if (!cursor || loadingOlder) return; const element = scrollRef.current; if (element) prependRef.current = { height: element.scrollHeight, top: element.scrollTop }; setLoadingOlder(true); setError(""); try { const response = await fetch(`/api/community-chat/messages?cursor=${encodeURIComponent(cursor)}`, { cache: "no-store" }); const page = await response.json() as Page; if (!response.ok) throw new Error(page.error ?? "Unable to load earlier messages."); setMessages((current) => sortMessages([...(page.messages ?? []), ...current])); setCursor(page.next_cursor ?? null); setHasMore(Boolean(page.has_more)); } catch (reason) { prependRef.current = null; setError(reason instanceof Error ? reason.message : "Unable to load earlier messages."); } finally { setLoadingOlder(false); } }
  function newest() { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" }); setUnread(0); }
  return <section aria-label="EarnGrind community chat" className="fixed inset-x-3 bottom-3 z-50 flex h-[min(42rem,calc(100dvh-1.5rem))] flex-col overflow-hidden rounded-[1.35rem] border border-slate-200 bg-white text-slate-900 shadow-[0_24px_80px_rgba(15,23,42,.18)] sm:inset-x-auto sm:bottom-0 sm:right-0 sm:h-dvh sm:w-[25rem] sm:rounded-none sm:border-y-0 sm:border-r-0">
    <header className="relative shrink-0 border-b border-slate-200 bg-white px-4 py-4"><div className="absolute inset-x-0 bottom-0 h-px bg-gradient-to-r from-transparent via-blue-500/60 to-transparent" /><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Circle aria-hidden className="h-2.5 w-2.5 fill-emerald-500 text-emerald-500" /><h2 className="text-sm font-bold tracking-tight text-slate-900">EarnGrind chat</h2></div><p className="mt-1 text-xs text-slate-500">Public conversation · sign in to join</p></div><button type="button" aria-label="Close chat" onClick={onClose} className="rounded-lg p-2 text-slate-500 transition hover:bg-slate-100 hover:text-slate-900 focus:outline-none focus:ring-2 focus:ring-blue-500"><X className="h-4 w-4" /></button></div></header>
    <div ref={scrollRef} onScroll={() => nearBottom() && setUnread(0)} className="flex-1 space-y-3 overflow-y-auto bg-[radial-gradient(circle_at_top,_rgba(59,130,246,.08),transparent_34%)] px-3 py-4">{hasMore ? <button type="button" onClick={() => void loadOlder()} disabled={loadingOlder} className="mx-auto block rounded-full border border-slate-200 bg-slate-50 px-3 py-1.5 text-xs font-semibold text-blue-700 transition hover:border-cyan-400/70 disabled:opacity-50">{loadingOlder ? "Loading earlier messages..." : "Load earlier messages"}</button> : messages.length ? <p className="py-1 text-center text-[11px] font-medium uppercase tracking-[.12em] text-slate-400">Start of conversation</p> : <p className="px-8 py-12 text-center text-sm text-slate-500">No messages yet. Be the first to welcome the community.</p>}{messages.map((message) => <article key={message.id} className="group flex gap-2.5"><ChatAvatar name={message.sender_name} src={message.sender_avatar_url} /><div className="min-w-0 flex-1"><div className="mb-1 flex items-center gap-2"><p className="truncate text-xs font-bold text-slate-800">{message.sender_name}</p>{message.can_delete ? <button type="button" aria-label="Remove message" disabled={deleting === message.id} onClick={() => void remove(message.id)} className="ml-auto rounded p-1 text-slate-400 opacity-0 transition hover:bg-rose-500/10 hover:text-rose-300 group-hover:opacity-100 focus:opacity-100 disabled:opacity-50"><Trash2 className="h-3.5 w-3.5" /></button> : null}</div><p className="whitespace-pre-wrap break-words rounded-2xl rounded-tl-md border border-slate-200 bg-slate-50 px-3 py-2 text-sm leading-relaxed text-slate-800 shadow-sm">{message.body}</p></div></article>)}{error ? <p role="alert" className="rounded-xl border border-rose-500/30 bg-rose-500/10 px-3 py-2 text-sm text-rose-200">{error}</p> : null}{unread ? <button type="button" onClick={newest} className="sticky bottom-2 mx-auto block rounded-full bg-blue-600 px-3 py-1.5 text-xs font-bold text-white shadow-lg shadow-cyan-500/20">{unread} new {unread === 1 ? "message" : "messages"}</button> : null}</div>
    <form onSubmit={send} className="shrink-0 border-t border-slate-200 bg-white p-3"><label className="sr-only" htmlFor="community-chat-message">Message</label><div className="rounded-xl border border-slate-200 bg-slate-50 p-2 transition focus-within:border-blue-500 focus-within:ring-2 focus-within:ring-blue-100"><textarea id="community-chat-message" value={body} maxLength={500} rows={2} disabled={!canPost} onCompositionStart={() => setComposing(true)} onCompositionEnd={() => setComposing(false)} onKeyDown={keydown} onChange={(event) => setBody(event.target.value)} placeholder={canPost ? "Share something helpful…" : "Sign in to join the conversation"} className="w-full resize-none bg-transparent px-1 py-0.5 text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none disabled:cursor-not-allowed disabled:text-slate-500" /><div className="mt-2 flex items-center justify-between gap-2"><span className="text-[11px] font-medium tabular-nums text-slate-500">{body.length}/500</span><button aria-label="Send message" disabled={!canPost || sending || !body.trim() || body.length > 500} className="inline-flex items-center gap-1.5 rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white transition hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-400 disabled:cursor-not-allowed disabled:opacity-40"><Send className="h-3.5 w-3.5" />{sending ? "Sending…" : "Send"}</button></div></div></form>
  </section>;
}