"use client";

import { Trash2, X } from "lucide-react";
import { FormEvent, KeyboardEvent, useCallback, useEffect, useLayoutEffect, useRef, useState } from "react";
import { supabase } from "@/lib/supabase/public";
import { trackEvent } from "@/lib/analytics";

type Message = { id: string; body: string; created_at: string; sender_name: string; sender_avatar_url: string | null; can_delete: boolean };
type Page = { messages?: Message[]; has_more?: boolean; next_cursor?: string | null; can_post?: boolean; error?: string };
type BroadcastInvalidation = { payload?: { message_id?: string; operation?: string } };
const sortMessages = (rows: Message[]) => Array.from(new Map(rows.map((row) => [row.id, row])).values()).sort((left, right) => left.created_at.localeCompare(right.created_at) || left.id.localeCompare(right.id));

export default function CommunityChatPanel({ onClose }: { onClose: () => void }) {
  const [messages, setMessages] = useState<Message[]>([]), [body, setBody] = useState(""), [error, setError] = useState(""), [sending, setSending] = useState(false), [deleting, setDeleting] = useState<string | null>(null), [composing, setComposing] = useState(false), [cursor, setCursor] = useState<string | null>(null), [hasMore, setHasMore] = useState(false), [loadingOlder, setLoadingOlder] = useState(false), [unread, setUnread] = useState(0), [canPost, setCanPost] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null), prependRef = useRef<{ height: number; top: number } | null>(null);
  const refresh = useCallback(async () => { const response = await fetch("/api/community-chat/messages", { cache: "no-store" }); const page = await response.json() as Page; if (!response.ok) throw new Error(page.error ?? "Chat is unavailable."); setMessages((current) => sortMessages([...current, ...(page.messages ?? [])])); setCursor((current) => current === null ? page.next_cursor ?? null : current); setHasMore((current) => current || Boolean(page.has_more)); setCanPost(Boolean(page.can_post)); }, []);
  const nearBottom = () => { const element = scrollRef.current; return !element || element.scrollHeight - element.scrollTop - element.clientHeight < 48; };
  useLayoutEffect(() => { const pending = prependRef.current, element = scrollRef.current; if (pending && element) { element.scrollTop = pending.top + (element.scrollHeight - pending.height); prependRef.current = null; } }, [messages]);
  useEffect(() => { let active = true; trackEvent("community_chat_open", { event_category: "engagement" }); refresh().catch(() => active && setError("Chat is unavailable right now.")); const channel = supabase.channel("community-chat").on("broadcast", { event: "chat_changed" }, (event: BroadcastInvalidation) => { if (!active) return; if (event.payload?.operation === "UPDATE" && event.payload.message_id) { setMessages((current) => current.filter((message) => message.id !== event.payload?.message_id)); return; } const wasNearBottom = nearBottom(); refresh().then(() => { if (wasNearBottom) scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight }); else setUnread((current) => current + 1); }).catch(() => undefined); }).subscribe((status) => { if (status === "CHANNEL_ERROR" || status === "TIMED_OUT") setError("Live updates are temporarily unavailable."); }); return () => { active = false; supabase.removeChannel(channel); }; }, [refresh]);
  async function send(event?: FormEvent) { event?.preventDefault(); if (!canPost || !body.trim() || body.length > 500 || sending) return; setSending(true); setError(""); try { const response = await fetch("/api/community-chat/messages", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ body, clientMessageId: crypto.randomUUID() }) }); const payload = await response.json(); if (!response.ok) { setError(payload.error ?? "Unable to send message."); await refresh(); return; } setBody(""); await refresh(); trackEvent("community_chat_send", { event_category: "engagement" }); } catch { setError("Unable to send message."); } finally { setSending(false); } }
  async function remove(id: string) { if (deleting) return; setDeleting(id); setError(""); try { const response = await fetch("/api/community-chat/messages", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ id }) }); if (!response.ok) { const payload = await response.json(); setError(payload.error ?? "Unable to remove message."); await refresh(); return; } setMessages((current) => current.filter((message) => message.id !== id)); } catch { setError("Unable to remove message."); } finally { setDeleting(null); } }
  function keydown(event: KeyboardEvent<HTMLTextAreaElement>) { if (event.key === "Enter" && !event.shiftKey && !composing) { event.preventDefault(); void send(); } }
  async function loadOlder() { if (!cursor || loadingOlder) return; const element = scrollRef.current; if (element) prependRef.current = { height: element.scrollHeight, top: element.scrollTop }; setLoadingOlder(true); setError(""); try { const response = await fetch(`/api/community-chat/messages?cursor=${encodeURIComponent(cursor)}`, { cache: "no-store" }); const page = await response.json() as Page; if (!response.ok) throw new Error(page.error ?? "Unable to load earlier messages."); setMessages((current) => sortMessages([...(page.messages ?? []), ...current])); setCursor(page.next_cursor ?? null); setHasMore(Boolean(page.has_more)); } catch (reason) { prependRef.current = null; setError(reason instanceof Error ? reason.message : "Unable to load earlier messages."); } finally { setLoadingOlder(false); } }
  function newest() { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" }); setUnread(0); }
  return <section aria-label="EarnGrind community chat" className="absolute bottom-16 right-0 flex h-[min(32rem,70vh)] w-[min(24rem,calc(100vw-2.5rem))] flex-col rounded-2xl border border-gray-200 bg-white shadow-2xl"><header className="flex items-center justify-between border-b p-4"><div><h2 className="font-bold">Community chat</h2><p className="text-xs text-gray-500">Read publicly. Sign in to contribute.</p></div><button type="button" aria-label="Close chat" onClick={onClose}><X className="h-5 w-5" /></button></header><div ref={scrollRef} onScroll={() => nearBottom() && setUnread(0)} className="flex-1 space-y-3 overflow-y-auto p-4">{hasMore ? <button type="button" onClick={() => void loadOlder()} disabled={loadingOlder} className="w-full text-xs font-semibold text-blue-700 disabled:opacity-50">{loadingOlder ? "Loading earlier messages..." : "Load earlier messages"}</button> : messages.length ? <p className="text-center text-xs text-gray-400">Start of conversation</p> : null}{messages.map((message) => <article key={message.id} className="group"><div className="flex items-center justify-between gap-2"><p className="text-xs font-semibold text-gray-700">{message.sender_name}</p>{message.can_delete ? <button type="button" aria-label="Remove message" disabled={deleting === message.id} onClick={() => void remove(message.id)} className="text-gray-400 hover:text-red-600 disabled:opacity-50"><Trash2 className="h-4 w-4" /></button> : null}</div><p className="whitespace-pre-wrap break-words text-sm text-gray-900">{message.body}</p></article>)}{error ? <p role="alert" className="text-sm text-red-600">{error}</p> : null}{unread ? <button type="button" onClick={newest} className="mx-auto block rounded-full bg-blue-600 px-3 py-1 text-xs font-semibold text-white">{unread} new {unread === 1 ? "message" : "messages"}</button> : null}</div><form onSubmit={send} className="border-t p-3"><label className="sr-only" htmlFor="community-chat-message">Message</label><textarea id="community-chat-message" value={body} maxLength={500} rows={2} disabled={!canPost} onCompositionStart={() => setComposing(true)} onCompositionEnd={() => setComposing(false)} onKeyDown={keydown} onChange={(event) => setBody(event.target.value)} placeholder={canPost ? "Write a message" : "Sign in to join the conversation"} className="w-full resize-none rounded-lg border px-3 py-2 text-sm disabled:bg-gray-50" /><div className="mt-2 flex items-center justify-between gap-2"><span className="text-xs text-gray-500">{body.length}/500</span><button disabled={!canPost || sending || !body.trim() || body.length > 500} className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{sending ? "Sending..." : "Send"}</button></div></form></section>;
}