-- EarnGrind Supabase Database Schema Reference
-- 
-- The authoritative schema definition is managed exclusively through versioned SQL migrations in:
--   supabase/migrations/ (77 migrations)
-- 
-- Active Domain Breakdown:
-- 1. Catalog & Aggregation: games, platforms, providers, offers, site_offers, site_offer_tasks, earn_offers, offer_partners
-- 2. User & Social: profiles, earn_user_profiles, user_gpt_partner_accounts, user_bookmarks, user_completions, community_chat_*
-- 3. Financial & Ledger: conversion_events, user_reward_ledger, earn_reward_support_tickets
-- 4. Traffic & Tracking: offer_clicks, site_offer_clicks, platform_clicks, revenue_events, guide_events, postback_receipts
-- 5. Views (Security Invoker): unified_offers_view, active_offers_view
-- 
-- To apply migrations locally:
--   npx supabase migration up
-- 
-- To generate TypeScript types:
--   npx supabase gen types typescript --local > src/types/database.types.ts
