"use client";

import Link from "next/link";
import { BarChart3, Calculator, Grid2X2, Menu, Search, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import type { ReactNode } from "react";
import { GPT_AFFILIATE_PLATFORMS } from "@/lib/gpt-affiliate-platforms";

type Props = { children: ReactNode; connectedCount: number };

export default function AccountAppShell({ children, connectedCount }: Props) {
    return <><style jsx global>{`body:has(.account-app-shell) > div > header, body:has(.account-app-shell) > div > footer, body:has(.account-app-shell) > div > a[href="#main-content"] { display: none; } body:has(.account-app-shell) { background: #f8f9fb; } .account-surface { border: 1px solid #dfe3e8; border-radius: 4px; background: #fff; box-shadow: 0 1px 2px rgba(15, 23, 42, .025); }`}</style><div className="account-app-shell min-h-screen bg-[#f8f9fb] text-slate-950">
        <aside className="account-sidebar fixed inset-y-0 left-0 z-40 hidden w-72 border-r border-slate-200 bg-white lg:flex lg:flex-col">
            <Link href="/" className="flex items-center gap-3 border-b border-slate-200 px-5 py-5">
                <span className="grid h-8 w-8 place-items-center rounded-md bg-lime-400 ring-2 ring-lime-300"><span className="h-2.5 w-2.5 rounded-full bg-slate-950" /></span>
                <span><strong className="block text-base tracking-tight">Earn<span className="text-lime-600">Grind</span> <em className="ml-1 rounded bg-lime-300 px-1 py-0.5 text-[9px] not-italic tracking-wider">PRO</em></strong><small className="block text-[11px] font-medium text-slate-500">Verified GPT & Offer Hub</small></span>
            </Link>
            <div className="px-4 pt-4"><Link href="/offers" className="flex items-center gap-2 border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-600"><Search size={14} /> Search offers & sites</Link></div>
            <nav className="mt-4 space-y-1 px-3" aria-label="Account workspace">
                <Link href="/account" className="flex items-center justify-between rounded-md bg-lime-400 px-3 py-2.5 text-xs font-extrabold text-slate-950"><span className="flex items-center gap-2"><UserRound size={15} /> Private Account & Perks</span><span className="text-[10px]">Active</span></Link>
                <Link href="/offers" className="flex items-center gap-2 rounded-md px-3 py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-100"><Sparkles size={15} /> Live Offer Wall</Link>
                <Link href="/best-gpt-sites" className="flex items-center gap-2 rounded-md px-3 py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-100"><Grid2X2 size={15} /> GPT Partner Matrix</Link>
                <Link href="/find-offers" className="flex items-center gap-2 rounded-md px-3 py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-100"><Calculator size={15} /> Payout Calculator</Link>
            </nav>
            <div className="mt-6 min-h-0 flex-1 overflow-y-auto border-t border-slate-100 px-3 pt-4"><div className="mb-3 flex items-center justify-between px-1 text-[10px] font-extrabold uppercase tracking-wider text-slate-500"><span>Quick signups</span><span>{connectedCount}/{GPT_AFFILIATE_PLATFORMS.length}</span></div><div className="space-y-2">{GPT_AFFILIATE_PLATFORMS.map((platform) => <a key={platform.slug} href={`/go/platform/${platform.slug}?click_location=account_sidebar&source_context=account_sidebar&platform_name=${encodeURIComponent(platform.name)}`} className="flex items-center justify-between gap-2 rounded-md border border-slate-200 bg-white px-2.5 py-2 text-xs font-bold text-slate-800 transition hover:border-lime-400 hover:bg-lime-50"><span className="min-w-0 truncate">{platform.name}</span><span className="rounded bg-slate-950 px-2 py-1 text-[9px] text-white">Join ↗</span></a>)}</div></div>
            <div className="border-t border-slate-200 p-3"><div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-[10px] font-bold text-slate-600"><span className="flex items-center justify-between"><span className="flex items-center gap-1"><ShieldCheck size={13} className="text-emerald-600" /> Private account</span><span>{connectedCount} active</span></span></div><Link href="/account/settings" className="mt-2 flex items-center justify-center gap-2 rounded-md border border-slate-300 bg-white py-2 text-xs font-extrabold text-slate-800">Settings</Link></div>
        </aside>
        <div className="lg:pl-72"><div className="hidden h-9 items-center gap-3 border-b border-slate-200 bg-white px-6 text-[11px] lg:flex"><span className="rounded border border-emerald-200 bg-emerald-50 px-2 py-0.5 font-extrabold uppercase tracking-wider text-emerald-700">● Live updates</span><span className="font-bold text-amber-600">⚡ Offer activity</span><span className="text-slate-500">Compare current routes before you commit.</span></div><header className="sticky top-0 z-30 flex h-14 items-center justify-between border-b border-slate-200 bg-white/95 px-4 backdrop-blur lg:px-8"><div className="flex items-center gap-2 text-sm font-extrabold"><Menu className="lg:hidden" size={18} /><span className="h-2 w-2 rounded-full bg-lime-400" /> Private Account & Perks</div><nav className="hidden items-center gap-6 text-xs font-bold text-slate-500 md:flex"><Link className="rounded bg-slate-950 px-3 py-2 text-white" href="/account">Account</Link><Link href="/offers">Live Offer Wall</Link><Link href="/best-gpt-sites">GPT Matrix</Link><Link href="/find-offers">Calculator</Link></nav><div className="flex items-center gap-3"><Link href="/offers" aria-label="Search offers" className="text-slate-600"><Search size={18} /></Link><span className="hidden rounded border border-emerald-200 bg-emerald-50 px-2 py-1 text-[10px] font-extrabold text-emerald-700 sm:inline">{connectedCount} routes active</span><Link href="/account" className="rounded bg-slate-950 px-3 py-2 text-xs font-extrabold text-white">Account</Link></div></header><main className="account-canvas px-4 py-6 sm:px-6 lg:px-10">{children}</main></div>
    </div></>;
}
