import { GPT_AFFILIATE_PLATFORMS, buildTrackedPlatformHref } from "@/lib/gpt-affiliate-platforms";

type PartnerConnection = { slug: string; connectedAt: string; lastSignupClickAt: string };
function dateLabel(value: string) { return new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(value)); }

export default function AccountPartnerSites({ connections }: { connections: PartnerConnection[] }) {
    const bySlug = new Map(connections.map((connection) => [connection.slug, connection]));
    return <section aria-labelledby="partner-sites"><div className="space-y-2"><p className="text-[11px] font-bold uppercase tracking-widest text-[var(--text-secondary)]">Partner signups</p><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 id="partner-sites" className="text-2xl font-extrabold tracking-tight text-[var(--brand-ink)]">Your GPT sites</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--text-secondary)]">Open a partner from here to use the EarnGrind affiliate signup link. We mark the link as opened; finish signup and any verification directly with that site.</p></div><span className="shrink-0 border border-[var(--border-default)] bg-[var(--surface-muted)] px-3 py-1.5 text-xs font-bold text-[var(--brand-ink)]">{connections.length} link{connections.length === 1 ? "" : "s"} opened</span></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{GPT_AFFILIATE_PLATFORMS.map((platform) => { const connection = bySlug.get(platform.slug); return <article key={platform.slug} className="flex min-w-0 flex-col border border-[var(--border-default)] bg-white p-5 shadow-[var(--shadow-card)] transition-shadow hover:shadow-[var(--shadow-hover)]"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="font-extrabold text-[var(--brand-ink)]">{platform.name}</h3><p className="mt-1 text-xs leading-5 text-[var(--text-secondary)]">{platform.bestFor}</p></div><span className={connection ? "shrink-0 border border-lime-300 bg-lime-50 px-2 py-1 text-[10px] font-extrabold uppercase tracking-wider text-lime-800" : "shrink-0 border border-[var(--border-default)] bg-[var(--surface-muted)] px-2 py-1 text-[10px] font-extrabold uppercase tracking-wider text-[var(--text-secondary)]"}>{connection ? "Link opened" : "Not started"}</span></div><p className="mt-4 text-sm leading-6 text-[var(--text-secondary)]">{platform.rewardNote}</p><p className="mt-4 min-h-8 text-[11px] leading-5 text-[var(--text-secondary)]">{connection ? <>First opened {dateLabel(connection.connectedAt)}{connection.lastSignupClickAt !== connection.connectedAt ? ` · Last opened ${dateLabel(connection.lastSignupClickAt)}` : ""}</> : "No partner signup link opened yet."}</p><a href={buildTrackedPlatformHref(platform, "account_partner_signup", "account_partner_signup")} className="mt-4 border border-[var(--brand-ink)] px-3 py-2.5 text-center text-xs font-bold text-[var(--brand-ink)] transition-colors hover:bg-[var(--brand-ink)] hover:text-white">{connection ? "Open signup link again" : platform.cta}</a></article>; })}</div></section>;
}
