import { GPT_AFFILIATE_PLATFORMS, buildTrackedPlatformHref } from "@/lib/gpt-affiliate-platforms";

type PartnerConnection = { slug: string; connectedAt: string; lastSignupClickAt: string };
function dateLabel(value: string) { return new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(value)); }

export default function AccountPartnerSites({ connections }: { connections: PartnerConnection[] }) {
    const bySlug = new Map(connections.map((connection) => [connection.slug, connection]));
    return <section aria-labelledby="partner-sites" className="account-partners"><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-extrabold uppercase tracking-widest text-slate-500">Partner signups</p><h2 id="partner-sites" className="mt-2 text-2xl font-black tracking-tight text-slate-950">Your GPT sites</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Open a partner from here to use the EarnGrind affiliate signup link. We mark the link as opened; finish signup and any verification directly with that site.</p></div><span className="w-fit rounded border border-slate-200 bg-white px-3 py-1.5 text-xs font-extrabold text-slate-800">{connections.length} links opened</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{GPT_AFFILIATE_PLATFORMS.map((platform) => { const connection = bySlug.get(platform.slug); return <article key={platform.slug} className="relative flex min-h-[300px] flex-col overflow-hidden rounded-md border border-slate-200 bg-white p-5 shadow-sm"><div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-emerald-500 to-lime-400" /><div className="flex items-center justify-between gap-3 pt-1"><span className="rounded border border-violet-200 bg-violet-50 px-2 py-1 text-[9px] font-extrabold uppercase tracking-wider text-violet-700">{platform.priority === "primary" ? "Mainstream" : "Partner"}</span><span className="rounded border border-slate-200 bg-slate-50 px-2 py-1 text-[9px] font-extrabold uppercase tracking-wider text-slate-600">{connection ? "Opened" : "Not started"}</span></div><div className="mt-5 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-md bg-slate-950 text-sm font-black text-lime-300">{platform.name.slice(0, 1)}</span><div><h3 className="font-black text-slate-950">{platform.name}</h3><p className="text-xs text-slate-500">{platform.bestFor}</p></div></div><p className="mt-4 text-sm leading-6 text-slate-600">{platform.rewardNote}</p><div className="mt-4 border-y border-slate-100 py-3 text-[11px] text-slate-500"><span className="font-bold text-slate-700">Direct affiliate link</span><br />{connection ? `First opened ${dateLabel(connection.connectedAt)}` : "Ready when you are."}</div><a href={buildTrackedPlatformHref(platform, "account_partner_signup", "account_partner_signup")} className="mt-auto rounded bg-black px-3 py-3 text-center text-xs font-extrabold text-white transition hover:bg-lime-400 hover:text-black">{connection ? "Open signup link again ↗" : `${platform.cta} ↗`}</a></article>; })}</div></section>;
}
