insert into public.platforms (
  id,
  name,
  slug,
  platform_kind,
  logo_url,
  description,
  countries,
  payout_methods,
  minimum_payout,
  affiliate_template,
  trust_score,
  is_active,
  bonus_headline
)
values
  (
    '71000000-0000-4000-8000-000000000001',
    'KashKick',
    'kashkick',
    'gpt_site'::public.platform_kind,
    null,
    'Cash-first GPT site for eligible U.S. users. Compare live terms before starting.',
    array['US'],
    array['PayPal', 'Venmo', 'Gift cards'],
    null,
    'https://app.kashkick.com?ref=MEF2ucEjcbtH',
    4.1,
    true,
    'Best beginner cash path'
  ),
  (
    '71000000-0000-4000-8000-000000000002',
    'Swagbucks',
    'swagbucks',
    'gpt_site'::public.platform_kind,
    null,
    'Mainstream rewards platform for surveys, shopping, games, search, PayPal, and gift-card style rewards.',
    array['US'],
    array['PayPal', 'Gift cards'],
    null,
    'https://www.swagbucks.com/profile/r_158565078?rp=1',
    4.3,
    true,
    'Best mainstream rewards site'
  ),
  (
    '71000000-0000-4000-8000-000000000003',
    'InboxDollars',
    'inboxdollars',
    'gpt_site'::public.platform_kind,
    null,
    'Cash-style rewards platform for surveys, games, offers, PayPal, Visa, and gift-card style payouts.',
    array['US'],
    array['PayPal', 'Visa', 'Gift cards'],
    null,
    'https://www.inboxdollars.com?rb=193664312',
    4.0,
    true,
    'Best cash-style backup'
  ),
  (
    '71000000-0000-4000-8000-000000000004',
    'MyPoints',
    'mypoints',
    'gpt_site'::public.platform_kind,
    null,
    'Shopping, surveys, email, video, points, PayPal, travel, and gift-card style rewards.',
    array['US'],
    array['PayPal', 'Gift cards', 'Travel miles'],
    null,
    'https://www.mypoints.com?rb=233983902',
    3.9,
    true,
    'Best shopping rewards backup'
  ),
  (
    '71000000-0000-4000-8000-000000000005',
    'PrizeRebel',
    'prizerebel',
    'gpt_site'::public.platform_kind,
    null,
    'Survey-heavy GPT site with PayPal, Bitcoin, and gift-card style rewards.',
    array[]::text[],
    array['PayPal', 'Bitcoin', 'Gift cards'],
    null,
    'https://www.prizerebel.com/index.php?r=16580973',
    3.9,
    true,
    'Best survey backup'
  ),
  (
    '71000000-0000-4000-8000-000000000006',
    'Scrambly',
    'scrambly',
    'gpt_site'::public.platform_kind,
    null,
    'Game and app discovery rewards site. Use referral code 3P5OXUA where prompted.',
    array[]::text[],
    array['PayPal', 'Visa', 'Gift cards'],
    null,
    'https://scrambly.io/',
    3.7,
    true,
    'Use referral code 3P5OXUA'
  ),
  (
    '71000000-0000-4000-8000-000000000007',
    'Gain.gg',
    'gain-gg',
    'gpt_site'::public.platform_kind,
    null,
    'Offerwall-style GPT site for comparing alternate routes.',
    array[]::text[],
    array['Rewards vary by account'],
    null,
    'https://gain.gg/r/macko',
    3.8,
    true,
    'High-payout offerwall backup'
  ),
  (
    '71000000-0000-4000-8000-000000000008',
    'GemLoot',
    'gemsloot',
    'gpt_site'::public.platform_kind,
    null,
    'Gaming offerwall backup for comparing alternate game payout routes.',
    array[]::text[],
    array['Rewards vary by account'],
    null,
    'https://gemsloot.com/?aff=kamedev',
    3.8,
    true,
    'Gaming offerwall backup'
  )
on conflict (slug) do update set
  name = excluded.name,
  platform_kind = excluded.platform_kind,
  logo_url = excluded.logo_url,
  description = excluded.description,
  countries = excluded.countries,
  payout_methods = excluded.payout_methods,
  minimum_payout = excluded.minimum_payout,
  affiliate_template = excluded.affiliate_template,
  trust_score = excluded.trust_score,
  is_active = excluded.is_active,
  bonus_headline = excluded.bonus_headline,
  updated_at = now()
returning id, name, slug, affiliate_template;
